stages:
  data_ingestion_stage:
    cmd: python -m email_spam_classification.data_ingestion
    deps:
      - email_spam_classification/data_ingestion.py
      - emails.csv
    outs:
      - data/raw/
  data_cleaning_stage:
    cmd: python -m email_spam_classification.data_cleaning
    deps:
      - data/raw/
      - email_spam_classification/data_cleaning.py
      - utils/text_cleaner.py
    params:
      - data_cleaning.test_size
    outs:
      - data/interim/
      - models/text_cleaner.pkl
  feature_engineering_stage:
    cmd: python -m email_spam_classification.feature_engineering
    deps:
      - data/interim/
      - email_spam_classification/feature_engineering.py
    params:
      - feature_engineering.type
      - feature_engineering.TfIdfVectorizer.ngram_range
      - feature_engineering.TfIdfVectorizer.max_features
    outs:
      - data/processed/
      - models/text_vectorizer.pkl
  model_building_stage:
    cmd: python -m email_spam_classification.model_building
    deps:
      - data/processed/
      - email_spam_classification/model_building.py
    params:
      - model_building.type
      - model_building.RandomForest.n_estimators
      - model_building.RandomForest.max_depth
      - model_building.RandomForest.min_samples_split
      - model_building.RandomForest.min_samples_leaf
      - model_building.RandomForest.random_state
    outs:
      - models/model.pkl
  model_evaluation_stage:
    cmd: python -m email_spam_classification.model_evaluation
    deps:
      - data/processed/
      - models/model.pkl
      - email_spam_classification/model_evaluation.py
    metrics:
      - metrics.json
