data_cleaning:
  test_size: 0.2

feature_engineering:
  type: TfIdfVectorizer

  TfIdfVectorizer:
    ngram_range: [1, 3]
    max_features: 10000

model_building:
  type: RandomForest

  RandomForest:
    n_estimators: 200
    max_depth: 30
    min_samples_split: 5
    min_samples_leaf: 10
    random_state: 42
    class_weight: balanced
