data_cleaning:
  test_size: 0.2

feature_engineering:
  type: TfIdfVectorizer

  TfIdfVectorizer:
    ngram_range: [1, 2]
    max_features: 1000

model_building:
  type: RandomForest

  RandomForest:
    n_estimators: 100
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
