name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
      DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}

    steps:
      - name: Checkout cod
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Security Check
        run: make security-check

      - name: Linting Check
        run: make linting-check

      - name: Formatting Check
        run: make format-check

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-2

      - name: Pull Data from AWS
        run: dvc pull

      - name: Run the pipeline
        run: dvc repro

      - name: Run tests
        run: pytest tests
